### ISSUE TITLE
JSHOP.jar file is not uploaded, MAKE file does not seam to be working

### ISSUE THREAD

**Issue by fahedAlkhabbas** [mas-group/jshop2#3]
Hi, 

First I would like to thank you for sharing the JSHOP2, I am really looking forward to using it. 
I downloaded the code and I am struggling in setting it up. First I could not find the JSHOP2.jar and the Makefile does not seam to work neither on Windows OS nor on MAC OS. Could you please advise ? I am grateful if you may send me more details on fahed.alkhabbas@mah.se

Thanks a lot. 

Best regards, 
Fahed

**Comment by sthoduka** [comment]
@fahedAlkhabbas please try the official download page for JSHOP2: https://sourceforge.net/projects/shop/files/JSHOP2/ (see also http://www.cs.umd.edu/projects/shop/description.html)

this repository is our local copy of JSHOP2, with our modifications. We have only tested on Linux as far as I know.
