### ISSUE TITLE
hello artur mas group

### ISSUE THREAD

**Issue by chuismiguel** [mas-group/jshop2#5]
i have terrible problem with your planner hope you can see it thank you

cd src/JSHOP2; java antlr.Tool JSHOP2.g; javac *.java
Error: Could not find or load main class antlr.Tool
Caused by: java.lang.ClassNotFoundException: antlr.Tool
JSHOP2Parser.java:9: error: package antlr does not exist
import antlr.TokenBuffer;
            ^
JSHOP2Parser.java:10: error: package antlr does not exist
import antlr.TokenStreamException;
            ^
JSHOP2Parser.java:11: error: package antlr does not exist
import antlr.TokenStreamIOException;
            ^
JSHOP2Parser.java:12: error: package antlr does not exist
import antlr.ANTLRException;
            ^
JSHOP2Parser.java:13: error: package antlr does not exist
import antlr.LLkParser;
            ^
JSHOP2Parser.java:14: error: package antlr does not exist
import antlr.Token;
            ^
JSHOP2Parser.java:15: error: package antlr does not exist
import antlr.TokenStream;
            ^
JSHOP2Parser.java:16: error: package antlr does not exist
import antlr.RecognitionException;
            ^
JSHOP2Parser.java:17: error: package antlr does not exist
import antlr.NoViableAltException;
            ^
JSHOP2Parser.java:18: error: package antlr does not exist
import antlr.MismatchedTokenException;
            ^
JSHOP2Parser.java:19: error: package antlr does not exist
import antlr.SemanticException;
            ^
JSHOP2Parser.java:20: error: package antlr does not exist
import antlr.ParserSharedInputState;
            ^
JSHOP2Parser.java:21: error: package antlr.collections.impl does not exist
import antlr.collections.impl.BitSet;
                             ^
JSHOP2Parser.java:23: error: package antlr does not exist
public class JSHOP2Parser extends antlr.LLkParser       implements JSHOP2TokenTypes
                                       ^
JSHOP2Lexer.java:10: error: package antlr does not exist
import antlr.TokenStreamException;
            ^
JSHOP2Lexer.java:11: error: package antlr does not exist
import antlr.TokenStreamIOException;
            ^
JSHOP2Lexer.java:12: error: package antlr does not exist
import antlr.TokenStreamRecognitionException;
            ^
JSHOP2Lexer.java:13: error: package antlr does not exist
import antlr.CharStreamException;
            ^
JSHOP2Lexer.java:14: error: package antlr does not exist
import antlr.CharStreamIOException;
            ^
JSHOP2Lexer.java:15: error: package antlr does not exist
import antlr.ANTLRException;
            ^
JSHOP2Lexer.java:18: error: package antlr does not exist
import antlr.CharScanner;
            ^
JSHOP2Lexer.java:19: error: package antlr does not exist
import antlr.InputBuffer;
            ^
JSHOP2Lexer.java:20: error: package antlr does not exist
import antlr.ByteBuffer;
            ^
JSHOP2Lexer.java:21: error: package antlr does not exist
import antlr.CharBuffer;
            ^
JSHOP2Lexer.java:22: error: package antlr does not exist
import antlr.Token;
            ^
JSHOP2Lexer.java:23: error: package antlr does not exist
import antlr.CommonToken;
            ^
JSHOP2Lexer.java:24: error: package antlr does not exist
import antlr.RecognitionException;
            ^
JSHOP2Lexer.java:25: error: package antlr does not exist
import antlr.NoViableAltForCharException;
            ^
JSHOP2Lexer.java:26: error: package antlr does not exist
import antlr.MismatchedCharException;
            ^
JSHOP2Lexer.java:27: error: package antlr does not exist
import antlr.TokenStream;
            ^
JSHOP2Lexer.java:28: error: package antlr does not exist
import antlr.ANTLRHashString;
            ^
JSHOP2Lexer.java:29: error: package antlr does not exist
import antlr.LexerSharedInputState;
            ^
JSHOP2Lexer.java:30: error: package antlr.collections.impl does not exist
import antlr.collections.impl.BitSet;
                             ^
JSHOP2Lexer.java:31: error: package antlr does not exist
import antlr.SemanticException;
            ^
JSHOP2Lexer.java:33: error: package antlr does not exist
public class JSHOP2Lexer extends antlr.CharScanner implements JSHOP2TokenTypes, TokenStream
                                      ^
JSHOP2Lexer.java:33: error: cannot find symbol
public class JSHOP2Lexer extends antlr.CharScanner implements JSHOP2TokenTypes, TokenStream
                                                                                ^
  symbol: class TokenStream
JSHOP2Parser.java:49: error: cannot find symbol
protected JSHOP2Parser(TokenBuffer tokenBuf, int k) {
                       ^
  symbol:   class TokenBuffer
  location: class JSHOP2Parser
JSHOP2Parser.java:54: error: cannot find symbol
public JSHOP2Parser(TokenBuffer tokenBuf) {
                    ^
  symbol:   class TokenBuffer
  location: class JSHOP2Parser
JSHOP2Parser.java:58: error: cannot find symbol
protected JSHOP2Parser(TokenStream lexer, int k) {
                       ^
  symbol:   class TokenStream
  location: class JSHOP2Parser
JSHOP2Parser.java:63: error: cannot find symbol
public JSHOP2Parser(TokenStream lexer) {
                    ^
  symbol:   class TokenStream
  location: class JSHOP2Parser
JSHOP2Parser.java:67: error: cannot find symbol
public JSHOP2Parser(ParserSharedInputState state) {
                    ^
  symbol:   class ParserSharedInputState
  location: class JSHOP2Parser
JSHOP2Parser.java:72: error: cannot find symbol
	public final void command() throws RecognitionException, TokenStreamException, IOException {
	                                   ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:72: error: cannot find symbol
	public final void command() throws RecognitionException, TokenStreamException, IOException {
	                                                         ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:78: error: cannot find symbol
	public final void prob() throws RecognitionException, TokenStreamException, IOException {
	                                ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:78: error: cannot find symbol
	public final void prob() throws RecognitionException, TokenStreamException, IOException {
	                                                      ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:189: error: cannot find symbol
	public final Predicate  la() throws RecognitionException, TokenStreamException {
	                                    ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:189: error: cannot find symbol
	public final Predicate  la() throws RecognitionException, TokenStreamException {
	                                                          ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:238: error: cannot find symbol
	public final TaskList  tl() throws RecognitionException, TokenStreamException {
	                                   ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:238: error: cannot find symbol
	public final TaskList  tl() throws RecognitionException, TokenStreamException {
	                                                         ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:329: error: cannot find symbol
	public final void domain() throws RecognitionException, TokenStreamException, IOException {
	                                  ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:329: error: cannot find symbol
	public final void domain() throws RecognitionException, TokenStreamException, IOException {
	                                                        ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:367: error: cannot find symbol
	public final void pde() throws RecognitionException, TokenStreamException {
	                               ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:367: error: cannot find symbol
	public final void pde() throws RecognitionException, TokenStreamException {
	                                                     ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:385: error: cannot find symbol
	public final void method() throws RecognitionException, TokenStreamException {
	                                  ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:385: error: cannot find symbol
	public final void method() throws RecognitionException, TokenStreamException {
	                                                        ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:492: error: cannot find symbol
	public final void op() throws RecognitionException, TokenStreamException {
	                              ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:492: error: cannot find symbol
	public final void op() throws RecognitionException, TokenStreamException {
	                                                    ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:566: error: cannot find symbol
	public final void axiom() throws RecognitionException, TokenStreamException {
	                                 ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:566: error: cannot find symbol
	public final void axiom() throws RecognitionException, TokenStreamException {
	                                                       ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:657: error: cannot find symbol
	public final List  terml() throws RecognitionException, TokenStreamException {
	                                  ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:657: error: cannot find symbol
	public final List  terml() throws RecognitionException, TokenStreamException {
	                                                        ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:691: error: cannot find symbol
	public final LogicalPrecondition  lp() throws RecognitionException, TokenStreamException {
	                                              ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:691: error: cannot find symbol
	public final LogicalPrecondition  lp() throws RecognitionException, TokenStreamException {
	                                                                    ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:784: error: cannot find symbol
	public final Vector  da() throws RecognitionException, TokenStreamException {
	                                 ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:784: error: cannot find symbol
	public final Vector  da() throws RecognitionException, TokenStreamException {
	                                                       ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:850: error: cannot find symbol
	public final Term  term() throws RecognitionException, TokenStreamException {
	                                 ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:850: error: cannot find symbol
	public final Term  term() throws RecognitionException, TokenStreamException {
	                                                       ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:976: error: cannot find symbol
	public final DelAddElement  dae() throws RecognitionException, TokenStreamException {
	                                         ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:976: error: cannot find symbol
	public final DelAddElement  dae() throws RecognitionException, TokenStreamException {
	                                                               ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:1097: error: cannot find symbol
	public final LogicalExpression  le() throws RecognitionException, TokenStreamException {
	                                            ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:1097: error: cannot find symbol
	public final LogicalExpression  le() throws RecognitionException, TokenStreamException {
	                                                                  ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:1339: error: cannot find symbol
	public final TaskAtom  ta() throws RecognitionException, TokenStreamException {
	                                   ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:1339: error: cannot find symbol
	public final TaskAtom  ta() throws RecognitionException, TokenStreamException {
	                                                         ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:1427: error: cannot find symbol
	public final String  fid() throws RecognitionException, TokenStreamException {
	                                  ^
  symbol:   class RecognitionException
  location: class JSHOP2Parser
JSHOP2Parser.java:1427: error: cannot find symbol
	public final String  fid() throws RecognitionException, TokenStreamException {
	                                                        ^
  symbol:   class TokenStreamException
  location: class JSHOP2Parser
JSHOP2Parser.java:1599: error: cannot find symbol
	public static final BitSet _tokenSet_0 = new BitSet(mk_tokenSet_0());
	                    ^
  symbol:   class BitSet
  location: class JSHOP2Parser
JSHOP2Parser.java:1604: error: cannot find symbol
	public static final BitSet _tokenSet_1 = new BitSet(mk_tokenSet_1());
	                    ^
  symbol:   class BitSet
  location: class JSHOP2Parser
JSHOP2Parser.java:1609: error: cannot find symbol
	public static final BitSet _tokenSet_2 = new BitSet(mk_tokenSet_2());
	                    ^
  symbol:   class BitSet
  location: class JSHOP2Parser
JSHOP2Parser.java:1614: error: cannot find symbol
	public static final BitSet _tokenSet_3 = new BitSet(mk_tokenSet_3());
	                    ^
  symbol:   class BitSet
  location: class JSHOP2Parser
JSHOP2Parser.java:1619: error: cannot find symbol
	public static final BitSet _tokenSet_4 = new BitSet(mk_tokenSet_4());
	                    ^
  symbol:   class BitSet
  location: class JSHOP2Parser
JSHOP2Parser.java:1624: error: cannot find symbol
	public static final BitSet _tokenSet_5 = new BitSet(mk_tokenSet_5());
	                    ^
  symbol:   class BitSet
  location: class JSHOP2Parser
JSHOP2Parser.java:1629: error: cannot find symbol
	public static final BitSet _tokenSet_6 = new BitSet(mk_tokenSet_6());
	                    ^
  symbol:   class BitSet
  location: class JSHOP2Parser
JSHOP2Parser.java:1634: error: cannot find symbol
	public static final BitSet _tokenSet_7 = new BitSet(mk_tokenSet_7());
	                    ^
  symbol:   class BitSet
  location: class JSHOP2Parser
JSHOP2Parser.java:1639: error: cannot find symbol
	public static final BitSet _tokenSet_8 = new BitSet(mk_tokenSet_8());
	                    ^
  symbol:   class BitSet
  location: class JSHOP2Parser
JSHOP2Parser.java:1644: error: cannot find symbol
	public static final BitSet _tokenSet_9 = new BitSet(mk_tokenSet_9());
	                    ^
  symbol:   class BitSet
  location: class JSHOP2Parser
JSHOP2Lexer.java:41: error: cannot find symbol
public JSHOP2Lexer(InputBuffer ib) {
                   ^
  symbol:   class InputBuffer
  location: class JSHOP2Lexer
JSHOP2Lexer.java:44: error: cannot find symbol
public JSHOP2Lexer(LexerSharedInputState state) {
                   ^
  symbol:   class LexerSharedInputState
  location: class JSHOP2Lexer
JSHOP2Lexer.java:64: error: cannot find symbol
public Token nextToken() throws TokenStreamException {
       ^
  symbol:   class Token
  location: class JSHOP2Lexer
JSHOP2Lexer.java:64: error: cannot find symbol
public Token nextToken() throws TokenStreamException {
                                ^
  symbol:   class TokenStreamException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:241: error: cannot find symbol
	public final void mAXIOM(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                      ^
  symbol:   class RecognitionException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:241: error: cannot find symbol
	public final void mAXIOM(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                                            ^
  symbol:   class CharStreamException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:241: error: cannot find symbol
	public final void mAXIOM(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                                                                 ^
  symbol:   class TokenStreamException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:254: error: cannot find symbol
	public final void mDIV(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                    ^
  symbol:   class RecognitionException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:254: error: cannot find symbol
	public final void mDIV(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                                          ^
  symbol:   class CharStreamException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:254: error: cannot find symbol
	public final void mDIV(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                                                               ^
  symbol:   class TokenStreamException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:267: error: cannot find symbol
	public final void mDOT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                    ^
  symbol:   class RecognitionException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:267: error: cannot find symbol
	public final void mDOT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                                          ^
  symbol:   class CharStreamException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:267: error: cannot find symbol
	public final void mDOT(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                                                               ^
  symbol:   class TokenStreamException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:280: error: cannot find symbol
	public final void mEQUAL(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                      ^
  symbol:   class RecognitionException
  location: class JSHOP2Lexer
JSHOP2Lexer.java:280: error: cannot find symbol
	public final void mEQUAL(boolean _createToken) throws RecognitionException, CharStreamException, TokenStreamException {
	                                                                            ^
  symbol:   class CharStreamException
  location: class JSHOP2Lexer
Note: JSHOP2Lexer.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
make: *** [Makefile:2: c] Error 1

thanks viva españa

**Comment by gbernalr** [comment]
you will not believe it, but i had the SAME error yesterday, unfortunately is not fixed yet.
Kisses from England!

**Comment by svenschneider** [comment]
Hi Luis,

FYI, we are not the original authors of this planner, but this is a fork of [JSHOP2](https://sourceforge.net/projects/shop/). We have just added some modifications to JIT-execute the generated planner.

In any case, to address your problem I think you have to setup the Java classpath correctly so that the compiler finds the antlr.jar file. The repository contains the classpath.sh script to do that setup. Sourcing that file should suffice, i.e. `source classpath.sh`.
Then the compilation with `make` should work as expected.

Please let me know if that solves your problem.

Best regards
Sven

**Comment by chuismiguel** [comment]
Really thank you mate, that solved the issue.
